import type { Metadata } from "next";

import DefaultLayout from "../DefaultLayout";

export const metadata: Metadata = {
  title: "Onboarding",
  description: "Generated by create next app",
};

export default function OnboardingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <DefaultLayout>{children}</DefaultLayout>;
}
